### ISSUE TITLE
Thanks for your work!

### ISSUE THREAD

**Issue by ZhymabekRoman** [TartexFumex/musecore2pdf#2]
Hi there. I'm an active MuseScore user and sometimes I need to download some pdf sheet music. And I developed Telegram bot that make easily download MuseScore sheet music. But for now it doesn't work and I made Telegram bot based on your backend.

https://github.com/ZhymabekRoman/musescore_pdf_downloader

Thanks.

**Comment by ZhymabekRoman** [comment]
But there is a problem, pages with more than one don't load. Probably MuseScore somehow detects the Selenium instance and just blocks. For example, [this](https://musescore.com/jmib/la-foule) downloads fine.

**Comment by TartexFumex** [comment]
Hi, 
Thank you for your feedback, I will try to fix that. Could you send me the Musecore pages that don't work?

**Comment by ZhymabekRoman** [comment]
Yes of course:
- https://musescore.com/user/30892962/scores/5592855
- https://musescore.com/user/385716/scores/5541987

**Comment by TartexFumex** [comment]
I think there is a problem with musecore. I tried to load these pages on different browsers/computers and with different French IP addresses but only the first page loaded. Is it the same on your usual browser?

**Comment by ZhymabekRoman** [comment]
> Is it the same on your usual browser?

Yes. Yesterday was absolutely normal.

**Comment by TartexFumex** [comment]
it's working again for me: 
[render.pdf](https://github.com/TartexFumex/musecore2pdf/files/14550551/render.pdf)
[render2.pdf](https://github.com/TartexFumex/musecore2pdf/files/14550553/render2.pdf)

**Comment by TartexFumex** [comment]
is it working for you now?

**Comment by ZhymabekRoman** [comment]
Sorry for the late response, sometimes pages load sometimes not, probably problem in MuseScore side, because some request get responses with status code 404.

Thanks!
